package cn.ac.iscas.nfs.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.6.10
 * 2013-11-29T17:05:46.844+08:00
 * Generated source version: 2.6.10
 * 
 */
@WebServiceClient(name = "ServiceImpl", 
                  wsdlLocation = "http://192.168.10.24:8089/bugReqRel?wsdl",
                  targetNamespace = "http://service.nfs.iscas.ac.cn/") 
public class ServiceImpl extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.nfs.iscas.ac.cn/", "ServiceImpl");
    public final static QName ServiceImplPort = new QName("http://service.nfs.iscas.ac.cn/", "ServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://192.168.10.24:8089/bugReqRel?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ServiceImpl.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://192.168.10.24:8089/bugReqRel?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ServiceImpl(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ServiceImpl(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServiceImpl() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ServiceImpl(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ServiceImpl(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ServiceImpl(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns ServiceInterface
     */
    @WebEndpoint(name = "ServiceImplPort")
    public ServiceInterface getServiceImplPort() {
        return super.getPort(ServiceImplPort, ServiceInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServiceInterface
     */
    @WebEndpoint(name = "ServiceImplPort")
    public ServiceInterface getServiceImplPort(WebServiceFeature... features) {
        return super.getPort(ServiceImplPort, ServiceInterface.class, features);
    }

}
