package cn.ac.iscas.nfs.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.0-milestone1
 * 2014-01-02T15:48:00.387+08:00
 * Generated source version: 3.0.0-milestone1
 * 
 */
@WebService(targetNamespace = "http://service.nfs.iscas.ac.cn/", name = "ServiceInterface")
@XmlSeeAlso({ObjectFactory.class})
public interface ServiceInterface {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "createBugReqRel", targetNamespace = "http://service.nfs.iscas.ac.cn/", className = "cn.ac.iscas.nfs.service.CreateBugReqRel")
    @WebMethod
    @ResponseWrapper(localName = "createBugReqRelResponse", targetNamespace = "http://service.nfs.iscas.ac.cn/", className = "cn.ac.iscas.nfs.service.CreateBugReqRelResponse")
    public boolean createBugReqRel(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getRelatedObjects", targetNamespace = "http://service.nfs.iscas.ac.cn/", className = "cn.ac.iscas.nfs.service.GetRelatedObjects")
    @WebMethod
    @ResponseWrapper(localName = "getRelatedObjectsResponse", targetNamespace = "http://service.nfs.iscas.ac.cn/", className = "cn.ac.iscas.nfs.service.GetRelatedObjectsResponse")
    public cn.ac.iscas.nfs.service.JsonObject getRelatedObjects(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getBugIdByReq", targetNamespace = "http://service.nfs.iscas.ac.cn/", className = "cn.ac.iscas.nfs.service.GetBugIdByReq")
    @WebMethod
    @ResponseWrapper(localName = "getBugIdByReqResponse", targetNamespace = "http://service.nfs.iscas.ac.cn/", className = "cn.ac.iscas.nfs.service.GetBugIdByReqResponse")
    public java.util.List<java.lang.String> getBugIdByReq(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getReqIdByBug", targetNamespace = "http://service.nfs.iscas.ac.cn/", className = "cn.ac.iscas.nfs.service.GetReqIdByBug")
    @WebMethod
    @ResponseWrapper(localName = "getReqIdByBugResponse", targetNamespace = "http://service.nfs.iscas.ac.cn/", className = "cn.ac.iscas.nfs.service.GetReqIdByBugResponse")
    public java.util.List<java.lang.String> getReqIdByBug(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2
    );
}
